name: Launch Application

on:
    push:
        branches:
            - "master" # to change later
    workflow_dispatch:
    # schedule:
    #   - cron: '0 0 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  call-reusable-workflow-dev:
    uses: a14T2n6g2l59Hgnsmb1Sc4L6CCY7U9XI2cmTor8/cloudhandson-eks-reusable-workflow/.github/workflows/reusable-workflow-tf-bootstrap.yaml@workflow_test
    with:
      CLUSTER_ENV: dev
      CLUSTER_NAME: mpft
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      GIT_TOKEN_PERSONAL: ${{ secrets.GIT_TOKEN_PERSONAL }}
#  call-reusable-workflow-qa:
#    needs: call-reusable-workflow-dev
#    uses: a14T2n6g2l59Hgnsmb1Sc4L6CCY7U9XI2cmTor8/cloudhandson-eks-reusable-workflow/.github/workflows/reusable-workflow-tf-bootstrap.yaml@workflow_test
#    with:
#      CLUSTER_ENV: qa
#    secrets:
#      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
#      GIT_TOKEN_PERSONAL: ${{ secrets.GIT_TOKEN_PERSONAL }}
#  call-reusable-workflow-preprod:
#    needs: call-reusable-workflow-qa
#    uses: a14T2n6g2l59Hgnsmb1Sc4L6CCY7U9XI2cmTor8/cloudhandson-eks-reusable-workflow/.github/workflows/reusable-workflow-tf-bootstrap.yaml@master
#    with:
#      CLUSTER_ENV: preprod
#    secrets:
#      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
#      GIT_TOKEN_PERSONAL: ${{ secrets.GIT_TOKEN_PERSONAL }}
#  call-reusable-workflow-prod:
#    needs: call-reusable-workflow-preprod
#    uses: a14T2n6g2l59Hgnsmb1Sc4L6CCY7U9XI2cmTor8/cloudhandson-eks-reusable-workflow/.github/workflows/reusable-workflow-tf-bootstrap.yaml@master
#    with:
#      CLUSTER_ENV: prod
#    secrets:
#      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
#      GIT_TOKEN_PERSONAL: ${{ secrets.GIT_TOKEN_PERSONAL }}
